import { Customer, Package } from '@/types';

export const samplePackages: Omit<Package, 'id'>[] = [
    {
        name: '1 Month',
        duration: 1,
        durationType: 'month',
        isDefault: true,
        createdAt: new Date('2024-01-01').toISOString() as any,
        updatedAt: new Date('2024-01-01').toISOString() as any,
    },
    {
        name: '3 Months',
        duration: 3,
        durationType: 'month',
        isDefault: true,
        createdAt: new Date('2024-01-01').toISOString() as any,
        updatedAt: new Date('2024-01-01').toISOString() as any,
    },
    {
        name: '1 Year',
        duration: 1,
        durationType: 'year',
        isDefault: true,
        createdAt: new Date('2024-01-01').toISOString() as any,
        updatedAt: new Date('2024-01-01').toISOString() as any,
    },
];

export const sampleCustomers: Omit<Customer, 'id'>[] = [
    {
        name: 'John Doe',
        email: 'john@example.com',
        phone: '+1234567890',
        serviceType: 'Premium Service',
        packageId: 'pkg-1',
        startDate: new Date('2024-11-01').toISOString() as any,
        endDate: new Date('2024-12-01').toISOString() as any,
        status: 'active',
        autoRenew: true,
        notes: 'VIP customer',
        createdAt: new Date('2024-11-01').toISOString() as any,
        updatedAt: new Date('2024-11-01').toISOString() as any,
    },
    {
        name: 'Jane Smith',
        email: 'jane@example.com',
        phone: '+0987654321',
        serviceType: 'Basic Service',
        packageId: 'pkg-2',
        startDate: new Date('2024-09-01').toISOString() as any,
        endDate: new Date('2024-12-01').toISOString() as any,
        status: 'active',
        autoRenew: false,
        notes: '',
        createdAt: new Date('2024-09-01').toISOString() as any,
        updatedAt: new Date('2024-09-01').toISOString() as any,
    },
    {
        name: 'Bob Wilson',
        email: 'bob@example.com',
        phone: '+1122334455',
        serviceType: 'Premium Service',
        packageId: 'pkg-1',
        startDate: new Date('2024-10-15').toISOString() as any,
        endDate: new Date('2024-10-20').toISOString() as any,
        status: 'expired',
        autoRenew: false,
        notes: 'Subscription expired',
        createdAt: new Date('2024-10-15').toISOString() as any,
        updatedAt: new Date('2024-10-15').toISOString() as any,
    },
    {
        name: 'Alice Johnson',
        email: 'alice@example.com',
        phone: '+5544332211',
        serviceType: 'Standard Service',
        packageId: 'pkg-3',
        startDate: new Date('2024-01-01').toISOString() as any,
        endDate: new Date('2025-01-01').toISOString() as any,
        status: 'active',
        autoRenew: true,
        notes: 'Annual subscription',
        createdAt: new Date('2024-01-01').toISOString() as any,
        updatedAt: new Date('2024-01-01').toISOString() as any,
    },
    {
        name: 'Charlie Brown',
        email: 'charlie@example.com',
        phone: '+6677889900',
        serviceType: 'Basic Service',
        packageId: 'pkg-1',
        startDate: new Date('2024-11-20').toISOString() as any,
        endDate: new Date('2024-12-05').toISOString() as any,
        status: 'expiring-soon',
        autoRenew: false,
        notes: 'Renewal reminder sent',
        createdAt: new Date('2024-11-20').toISOString() as any,
        updatedAt: new Date('2024-11-20').toISOString() as any,
    },
];
